server:
  port: 10013
  servlet:
    context-path: /app3

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  server:
    servlet:
      context-path: ${server.servlet.context-path}
    port: ${server.port}
  endpoint:
    health:
      show-details: always

# 定义一个端点，用于健康检查。
# url：localhost:10013/app3/info
info: { status: ok }
