apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: httpbackend-v1
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: httpbackend
      version: v1
  template:
    metadata:
      labels:
        app: httpbackend
        version: v1
    spec:
      containers:
      - name: httpbackend
        image: bigwhite/httpbackendservice:v1.0.0
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: httpbackend-v2
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: httpbackend
      version: v2
  template:
    metadata:
      labels:
        app: httpbackend
        version: v2
    spec:
      containers:
      - name: httpbackend
        image: bigwhite/httpbackendservice:v2.0.0
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: httpbackend
  labels:
    app: httpbackend
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: httpbackend
