spring:
  application:
    name: sso1-server
#  security:
#    user:
#      # \u8D26\u53F7
#      name: cpq
#      # \u5BC6\u7801
#      password: cpq123456
#  datasource:
#    url: jdbc:mysql://localhost:3306/cpq?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: cpq..123
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
server:
  port: 8080
