<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cpq</groupId>
  <artifactId>spring-ai-alibaba-01</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <java.version>21</java.version>
    <!-- Spring Boot 新建2025.9-->
    <spring-boot.version>3.5.5</spring-boot.version>
    <!-- Spring AI 新建2025.9-->
    <spring-ai.version>1.0.0</spring-ai.version>
    <!-- Spring AI Alibaba 新建2025.9-->
    <SpringAIAlibaba.version>1.0.0.2</SpringAIAlibaba.version>
  </properties>

  <modules>
    <module>SAA-01HelloWorld</module>
    <module>SAA-02Ollama</module>
    <module>SAA-03ChatModelChatClient</module>
    <module>SAA-04StreamingOutput</module>
    <module>SAA-05Prompt</module>
    <module>SAA-06PromptTemplate</module>
    <module>SAA-07StructuredOutput</module>
    <module>SAA-08Persistent</module>
    <module>SAA-09Text2image</module>
    <module>SAA-10Text2voice</module>
    <module>SAA-11Embed2vector</module>
    <module>SAA-12RAG4AiOps</module>
    <module>SAA-13ToolCalling</module>
    <module>SAA-14LocalMcpServer</module>
    <module>SAA-15LocalMcpClient</module>
    <module>SAA-16ClientCallBaiduMcpServer</module>
    <module>SAA-17BailianRAG</module>
    <module>SAA-18TodayMenu</module>
  </modules>


  <dependencyManagement>
    <dependencies>
      <!-- Spring Boot -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring AI Alibaba -->
      <dependency>
        <groupId>com.alibaba.cloud.ai</groupId>
        <artifactId>spring-ai-alibaba-bom</artifactId>
        <version>${SpringAIAlibaba.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring AI -->
      <dependency>
        <groupId>org.springframework.ai</groupId>
        <artifactId>spring-ai-bom</artifactId>
        <version>${spring-ai.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>


  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring-boot.version}</version>
      </plugin>
    </plugins>
  </build>

  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>


</project>
