apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: app01
        imagePullPolicy: Always
        image: codingsoldier/app01:latest
        ports:
        - name: http
          containerPort: 10011
---
apiVersion: v1
kind: Service
metadata:
  name: service-app01
spec:
  selector:
    app: app01
  ports:
  - name: http
    port: 10011
    targetPort: 10011

