server.port=8014

# \u8BBE\u7F6E\u5168\u5C40\u7F16\u7801\u683C\u5F0F
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=SAA-14LocalMcpServer


# ====mcp-server Config=============
spring.ai.mcp.server.type=async
spring.ai.mcp.server.name=local-mcp-1
spring.ai.mcp.server.version=1.0.0