spring:
  application:
    name: sso1-server
#  security:
#    user:
#      # \u8D26\u53F7
#      name: cpq
#      # \u5BC6\u7801
#      password: cpq123456
#  datasource:
#    url: jdbc:mysql://localhost:3306/cpq?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#    driverClassName: com.mysql.jdbc.Driver
#    username: root
#    password: cpq..123
  redis:
    host: localhost
#    host: 192.168.4.205
    port: 6379
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
server:
  port: 8080
