spring:
  application:
    name: config-server
  cloud:
    config:
      username: CodingSoldier
      password: dszgmml2ss103
      label: master
      server:
        git:
          uri: https://github.com/CodingSoldier/spring-cloud-config-git.git
          # application作为一个占位符，获取服务名，用这个服务名匹配git仓库中的文件夹
          searchPaths: '{application}'
          # 强制从远程git仓库获取配置
          force-pull: true

# 浏览器打开 http://localhost:1201/config-client/dev/master
# 加载的是https://github.com/CodingSoldier/spring-cloud-config-git.git
# master分支中的config-client.yml、config-client-dev.yml配置文件

# 浏览器打开 http://localhost:1201/config-client/test/master
# 加载的是https://github.com/CodingSoldier/spring-cloud-config-git.git
# master分支中的config-client.yml、config-client-test.yml配置文件

# 若打开 http://localhost:1201/config-client/master  这url不规范，需要加上环境的profile
# 仅仅加载 https://github.com/CodingSoldier/spring-cloud-config-git.git
# master分支中的 config-client.yml配置文件

#*************其他工程获取git上的配置请查看：config-client、eureka-consumer*****************#

server:
  port: 1201