spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  data:
    redis:
      host: 192.168.1.221
      port: 6379
  ai:
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        request-timeout: 60s
        type: ASYNC
        sse:
          connections:
            # 通过sse使用远程mcp服务，高德地图mcp服务
            server1:
              url: https://mcp.amap.com
              sse-endpoint: /sse?key=bfd7f79a957f12846678ed71b420565c
            # 是用本地开发的mcp服务
            server2:
              url: http://localhost:9060
              sse-endpoint: /sse
        stdio:
          # 本地通过stdio使用mcp服务
          servers-configuration: classpath:mcp-server.json
    openai:
      api-key: ${ALI_AI_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus
      embedding:
        enabled: true
        options:
          model: text-embedding-v4
    vectorstore:
      redis:
        initialize-schema: true         # 是否初始化所需的模式
        index-name: lee-vectorstore     # 用于存储向量的索引名称
        prefix: 'embedding:'            # Redis 键的前缀

logging:
  level:
    root: info

# SearXNG联网搜索
internet:
  websearch:
    searxng:
      url: http://192.168.1.221:8888/search
      counts: 10