spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  data:
    redis:
      host: 192.168.1.221
      port: 6379
#      password: 123456
  ai:
#    mcp:
#      client:
#        enabled: true
#        name: spring-ai-mcp-client
#        type: ASYNC
#        sse:
#          connections:
#            server1:
#              url: https://mcp.amap.com
#              sse-endpoint: /sse?key=09557e21174fff33be82c6cf0fa2cbcb
#            server2:
#              url: http://localhost:9060
#              sse-endpoint: /sse
#        stdio:
#          servers-configuration: classpath:mcp-server.json
    openai:
      api-key: ${ALI_AI_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus
    vectorstore:
      redis:
        initialize-schema: true         # 是否初始化所需的模式
        index-name: lee-vectorstore     # 用于存储向量的索引名称
        prefix: 'embedding:'             # Redis 键的前缀

logging:
  level:
    root: info

#internet:
#  websearch:
#    searxng:
#      url: http://localhost:6080/search
#      counts: 10