config.yaml
  apiVersion: kubeadm.k8s.io/v1alpha1
  kind: MasterConfiguration
  api:
    advertiseAddress: <lb-virtual-ip>
    controlPlaneEndpoint: <lb-virtual-ip>
  etcd:
    endpoints:
    - https://<etcd0-ip-address>:2379
    - https://<etcd1-ip-address>:2379
    - https://<etcd2-ip-address>:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/etcd/client.crt
    keyFile: /etc/kubernetes/pki/etcd/client.key
  networking:
    podSubnet: <podCIDR>
  apiServerCertSANs:
  - <lb-virtual-ip>
  - <private-ip>
  apiServerExtraArgs:
    apiserver-count: "3"
