server.port=8007

#\u4E2D\u6587\u4E71\u7801\u56DE\u590D
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=SAA-07StructuredOutput

# ====SpringAIAlibaba Config=============
spring.ai.dashscope.api-key=${ALI_AI_KEY}