apiVersion: tco.coreos.com/v1
kind: AppVersion
metadata:
  name: tectonic-cluster
  namespace: tectonic-system
  labels:
    managed-by-channel-operator: "true"
  annotations:
    tectonic-operators.coreos.com/upgrade-behaviour: 'CreateOrUpgrade'
spec:
  desiredVersion: 1.7.5+tectonic.1
  paused: false
status:
  currentVersion: 1.7.5+tectonic.1
  paused: false
