apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "channeloperatorconfigs.tco.coreos.com"
spec:
  group: "tco.coreos.com"
  version: "v1"
  names:
    plural: "channeloperatorconfigs"
    kind: "ChannelOperatorConfig"
