#yml代码提示需要添加YAML/Ansible support插件
server:
   port: ${server.port}

logging:
  file: log/spring-boot-learn.log
#  level:
#    com:
#      demo: DEBUG


spring:
  application:
    name: spring-boot-learn
  profiles:
    active: {spring.profiles.active}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
