#yml代码提示需要添加YAML/Ansible support插件
server:
  port: 8081

logging:
  file: log/spring-boot-learn.log
#  level:
#    com:
#      demo: DEBUG


spring:
  application:
    name: spring-boot-learn
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: cpq..123


test:
  val: aaa