server:
   port: 8082

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: cpq..123