spring:
  application:
    name: api-gateway

server:
  port: 1001

eureka:
  #instance:
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
            #设置API网关中路由转发请求的HystrixCommand执行超时时间

ribbon:
  ConnectTimeout: 10000 #设置路由转发请求的时候，创建请求连接的超时时间
  ReadTimeout: 30000   #用来设置路由转发请求的超时时间

zuul:
  #将api-gateway中将Cookie,Set-Cookie,Authorization传递给下游服务
  #https://blog.csdn.net/chenqipc/article/details/53322830
  sensitiveHeaders:
  routes:
    # eureka-client服务有多个，以/eureka-client/开头的请求转发到服务名为eureka-client的服务中。
    # /eureka-client请求前缀会被去掉，#即 http://localhost:1001/eureka-client/dc 转发到 http://localhost:2001/dc
    eureka-client:
      path: /eureka-client/**

    # websocket失败
    api-websocket:
      path: /ws/**
      serviceId: api-websocket
      # url: http://localhost:1100/websocket
