server:
  port: 10005

spring:
  application:
    name: api-gateway
  cloud:

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: TO_APP01
          uri: lb://app001
          predicates:
            - Path=/app001/**
          filters:
            - StripPrefix=1
        - id: TO_APP02
          uri: lb://app002
          predicates:
            - Path=/app002/**
          filters:
            - StripPrefix=1
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
      probability: 1.0
  zipkin:
    # 指定了 Zipkin 服务器的地址
    base-url: http://localhost:9411/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      instance-id: ${spring.application.name}:${server.port}
#      defaultZone: http://localhost:10001/eureka/, http://localhost:10002/eureka/, http://localhost:10003/eureka/
      defaultZone: http://localhost:10001/eureka/

# 启动熔断器，设置总超时、服务调用超时时间，超时则熔断
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 32000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 30000
