server.port=8017

# \u8BBE\u7F6E\u5168\u5C40\u7F16\u7801\u683C\u5F0F
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8

spring.application.name=SAA-17BailianRAG


# ====SpringAIAlibaba Config=============
spring.ai.dashscope.api-key=${ALI_AI_KEY}
